# ワークフロー名
name: Production_Build
on:
  schedule:
    # 定期実行する時間
    # 日本時間では 03:00 / 09:00 / 15:00 / 21:00 ごろに実行
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEPLOY_HOOK_URL: ${{secrets.DEPLOY_HOOK_URL}}
    steps:
      - name: Run script
        run: |
          curl -X POST $DEPLOY_HOOK_URL
